### ISSUE TITLE
Love this package

### ISSUE THREAD

**Issue by leelandmiller** [tehapo/atom-tag-wrapper#5] opened 2017-08-10 19:34 UTC
I've used atom-wrap-in-tag for a long while now.
My gripe was that if i would wrap multiple lines, it would not indent.
So I switched to your package, atom-tag-wrapper. Love that I don't have to manually indent my new wrapping tags; it nearly took more time for me to manually indent after wrapping that it would have to just not use the tool at all.

Example:

```
<h1>Heading</h1>
<p>A paragraph</p>
```
would wrap like this in atom-wrap-in-tag:

```
<div><h1>Heading</h1>
<p>A paragraph</p></div>
```

Whereas atom-tag-wrapper wraps as it should, like this:
```
<div>
  <h1>Heading</h1>
  <p>A paragraph</p>
</div>
```

My only issue with atom-tag-wrapper:

After inserting a new wrapping tag and editing the tag type, when I hit `space`, in my opinion, it should be assumed that I am going to begin typing some sort of attribute(s). So again, my opinion, it should automatically deselect the closing wrapping tag so that I can begin typing my attributes without having to deselect the closing tag manually.

**Comment by tehapo** [comment] 2017-08-10 19:57
You're right, hitting space should definitely deselect the closing tag. Unfortunately I haven't had time to implement this yet, but I hope to do it soon.

Closing this issue as it is a duplicate of #4

**Closed as completed by tehapo** 2017-08-10 19:57 UTC

**Comment by leelandmiller** [comment] 2017-08-10 20:28
glad to hear it's in the works! thanks
